language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  composer test
