language: php

php:
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  composer test

after_script:
 - cat rarus-bonus-service-integration-tests.log
 - curl -i -H "Accept: application/json" -H "Content-Type: application/json; charset=utf-8" -H "token: 725B4F58989543EA92A261B2C8C877A8" https://demo.bonus.rarus-online.com:88/organization/shop